version: '3'
services:
   db:
        #image: mysql
        build: ./mysql
        ports:
        - "3306:3306"
        environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=bvs     
        - MYSQL_USER=root
        volumes:
        - ./data.sql:/docker-entrypoint-initdb.d/init.sql
   web:
        build: ./app
        ports:
        - "8080:8080"
        links:
        - "db:db"
        environment:
        - DATABASE_HOST=db
        depends_on:
        - "db"
        entrypoint: python bvs.py
        #command: ["./wait_for_db.py", "python", "bvs.py"]
   nginx:
        restart: always
        build: ./nginx/
        ports:
        - "80:80"
        volumes:
        - /www/static
        links:
        - web:web
